(*----------------------------------------------------------------------*)
(*        Do_Xmodem_Download --- Controls Xmodem downloads              *)
(*----------------------------------------------------------------------*)

PROCEDURE Do_Xmodem_Download( Trans_Protocol : Transfer_Type );

(*----------------------------------------------------------------------*)
(*                                                                      *)
(*     Procedure:  Do_Xmodem_Download                                   *)
(*                                                                      *)
(*     Purpose:    Controls Xmodem-family downloads                     *)
(*                                                                      *)
(*     Calling Sequence:                                                *)
(*                                                                      *)
(*        Do_Xmodem_DownLoad( Trans_Protocol : Transfer_Type );         *)
(*                                                                      *)
(*           Trans_Protocol --- type of transfer to do                  *)
(*                                                                      *)
(*----------------------------------------------------------------------*)

