(*----------------------------------------------------------------------*)
(*           Do_Xmodem_Upload --- Controls Xmodem uploads               *)
(*----------------------------------------------------------------------*)

PROCEDURE Do_Xmodem_Upload( Trans_Protocol : Transfer_Type );

(*----------------------------------------------------------------------*)
(*                                                                      *)
(*     Procedure:  Do_Xmodem_Upload                                     *)
(*                                                                      *)
(*     Purpose:    Controls Xmodem-family uploads                       *)
(*                                                                      *)
(*     Calling Sequence:                                                *)
(*                                                                      *)
(*        Do_Xmodem_UpLoad( Trans_Protocol : Transfer_Type );           *)
(*                                                                      *)
(*           Trans_Protocol --- type of transfer to do                  *)
(*                                                                      *)
(*----------------------------------------------------------------------*)
