(*----------------------------------------------------------------------*)
(*          EMULTUSR.PAS --- Emulate User Terminal for PIBTERM          *)
(*----------------------------------------------------------------------*)

PROCEDURE Emulate_User_Terminal;

(*----------------------------------------------------------------------*)
(*                                                                      *)
(*     Procedure:  Emulate_User_Terminal                                *)
(*                                                                      *)
(*     Purpose:    Controls user terminal emulation                     *)
(*                                                                      *)
(*     Calling Sequence:                                                *)
(*                                                                      *)
(*        Emulate_User_Terminal;                                        *)
(*                                                                      *)
(*      Remarks:                                                        *)
(*                                                                      *)
(*         You can replace this with something your own terminal        *)
(*         emulation code.  Right now it simply calls dumb terminal.    *)
(*                                                                      *)
(*----------------------------------------------------------------------*)

BEGIN (* Emulate_User_Terminal *)
END   (* Emulate_User_Terminal *);
