(*----------------------------------------------------------------------*)
(*            Receive_Rlink_File --- Downloads file with Rlink          *)
(*----------------------------------------------------------------------*)

PROCEDURE Receive_Rlink_File;

(*----------------------------------------------------------------------*)
(*                                                                      *)
(*     Procedure:  Receive_Rlink_File                                   *)
(*                                                                      *)
(*     Purpose:    Downloads files using Rlink                          *)
(*                                                                      *)
(*     Calling Sequence:                                                *)
(*                                                                      *)
(*        Receive_Rlink_File;                                           *)
(*                                                                      *)
(*     Calls:                                                           *)
(*                                                                      *)
(*     Remarks:                                                         *)
(*                                                                      *)
(*                                                                      *)
(*----------------------------------------------------------------------*)

BEGIN (* Receive_Rlink_File *)

END   (* Receive_Rlink_File *);
