(*----------------------------------------------------------------------*)
(*        Receive_WXmodem_File --- Downloads file with WXmodem          *)
(*----------------------------------------------------------------------*)

PROCEDURE Receive_WXmodem_File;

(*----------------------------------------------------------------------*)
(*                                                                      *)
(*     Procedure:  Receive_WXmodem_File                                 *)
(*                                                                      *)
(*     Purpose:    Downloads files using WXmodem                        *)
(*                                                                      *)
(*     Calling Sequence:                                                *)
(*                                                                      *)
(*        Receive_WXmodem_File;                                         *)
(*                                                                      *)
(*     Calls:                                                           *)
(*                                                                      *)
(*     Remarks:                                                         *)
(*                                                                      *)
(*                                                                      *)
(*----------------------------------------------------------------------*)

BEGIN (* Receive_WXmodem_File *)

END   (* Receive_WXmodem_File *);
