(*----------------------------------------------------------------------*)
(*        Send_WXmodem_File --- Uploads file with WXmodem               *)
(*----------------------------------------------------------------------*)

PROCEDURE Send_WXmodem_File;

(*----------------------------------------------------------------------*)
(*                                                                      *)
(*     Procedure:  Send_WXmodem_File                                    *)
(*                                                                      *)
(*     Purpose:    Uploads files using WXmodem                          *)
(*                                                                      *)
(*     Calling Sequence:                                                *)
(*                                                                      *)
(*        Send_WXmodem_File;                                            *)
(*                                                                      *)
(*     Calls:                                                           *)
(*                                                                      *)
(*     Remarks:                                                         *)
(*                                                                      *)
(*                                                                      *)
(*----------------------------------------------------------------------*)

BEGIN (* Send_WXmodem_File *)

END   (* Send_WXmodem_File *);
